#include "nsISupports.idl"

[scriptable, uuid(9FFB204D-74C9-44a0-867F-FDEBDD89EB1E)]
interface nsIPCMan : nsISupports {
  void connect( in string url );
  void setFontFace( in wstring name ); // name of font
  void setFontFaceEn( in wstring name ); // 
  void setFontSize( in short size ); // 0 means auto
  void setAntiIdle( in long idleTime, in string idleString ); // idleTime = 0 means turn off
  void setEscape( in string esc ); // Default: ^U
  void setAutoDbcsDetection( in PRUint32 value );
  void setSearchEngineData( in string url, in string param_name, in PRUint32 num );
  void setUseMouseBrowsing( in boolean value );
  void setUseTextDragDrop( in boolean value );
  void setLoadUrlInBackGround( in boolean value );
  void setGesturesSensitivityX( in PRUint32 value );
  void setGesturesUseXAxisOnly( in boolean value );
  void setUseHelperWnd( in boolean value );
  void setUseMouseWheelHack( in boolean value );
  void setMouseOverEffect( in PRUint32 value );
  void focus();
  long getHWND();
};

